/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#7a440e",
        "surface-tint": "#0b9fcc",
        "secondary-fixed": "#f6dcc1",
        "tertiary-fixed-dim": "#efac6f",
        "surface-container-low": "#eef7fa",
        "on-surface": "#191c1e",
        outline: "#71848d",
        "primary-fixed-dim": "#8ddcf2",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#ddebf0",
        "on-secondary": "#ffffff",
        "surface-bright": "#f8fcfd",
        "surface-container": "#e7f1f5",
        "on-error": "#ffffff",
        error: "#ba1a1a",
        "inverse-on-surface": "#eff1f3",
        primary: "#0b9fcc",
        "secondary-container": "#f5d2b4",
        "on-tertiary-fixed": "#281900",
        secondary: "#c96f1c",
        "surface-dim": "#d6e4e8",
        "outline-variant": "#c2d4db",
        "on-primary-fixed": "#002b39",
        "secondary-fixed-dim": "#e8b483",
        "inverse-primary": "#8ddcf2",
        "on-primary": "#ffffff",
        "on-secondary-fixed": "#4d2700",
        "on-primary-container": "#d2f3fb",
        "on-tertiary": "#ffffff",
        "primary-fixed": "#d2f3fb",
        "on-secondary-fixed-variant": "#8e4d11",
        "tertiary-fixed": "#ffd9b8",
        "primary-container": "#087897",
        surface: "#f8fcfd",
        "on-primary-fixed-variant": "#066e8a",
        "surface-variant": "#dde8ec",
        "on-error-container": "#93000a",
        "on-tertiary-fixed-variant": "#6a3907",
        "on-background": "#191c1e",
        "surface-container-highest": "#d8e7eb",
        background: "#f8fcfd",
        "on-secondary-container": "#6c3700",
        "inverse-surface": "#2d3133",
        tertiary: "#7a440e",
        "on-tertiary-container": "#ffe3ca",
        "error-container": "#ffdad6",
        "on-surface-variant": "#43474f",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      boxShadow: {
        editorial: "0 20px 40px rgba(11, 159, 204, 0.10)",
        "editorial-xl": "0 30px 60px rgba(11, 159, 204, 0.16)",
      },
    },
  },
  plugins: [],
};
