/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "outline-variant": "#c3c6d0",
        "on-error-container": "#93000a",
        "surface-variant": "#e0e3e5",
        "on-primary-fixed": "#001c3a",
        "inverse-surface": "#2d3133",
        "on-tertiary-container": "#edbc6c",
        "on-tertiary-fixed": "#281900",
        "on-surface-variant": "#43474f",
        secondary: "#3c6752",
        "primary-fixed": "#d4e3ff",
        "on-secondary-fixed-variant": "#244f3b",
        "error-container": "#ffdad6",
        "on-surface": "#191c1e",
        "on-secondary": "#ffffff",
        "on-primary-fixed-variant": "#204877",
        "on-background": "#191c1e",
        "tertiary-fixed-dim": "#f0be6e",
        "tertiary-container": "#6d4a00",
        "surface-container-high": "#e6e8ea",
        "on-tertiary": "#ffffff",
        "on-primary": "#ffffff",
        "on-secondary-container": "#406b56",
        "on-primary-container": "#a2c6fd",
        "surface-dim": "#d8dadc",
        "primary-container": "#2c5282",
        "surface-container": "#eceef0",
        primary: "#0e3b69",
        "tertiary-fixed": "#ffdead",
        tertiary: "#4f3500",
        error: "#ba1a1a",
        "secondary-fixed": "#beedd3",
        "inverse-on-surface": "#eff1f3",
        background: "#f7f9fb",
        "surface-container-lowest": "#ffffff",
        "on-error": "#ffffff",
        "secondary-container": "#bbead0",
        "surface-container-highest": "#e0e3e5",
        "surface-bright": "#f7f9fb",
        "surface-container-low": "#f2f4f6",
        "on-tertiary-fixed-variant": "#604100",
        "surface-tint": "#3b6090",
        "primary-fixed-dim": "#a5c8ff",
        surface: "#f7f9fb",
        "secondary-fixed-dim": "#a2d1b7",
        "on-secondary-fixed": "#002114",
        "inverse-primary": "#a5c8ff",
        outline: "#737780",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      boxShadow: {
        editorial: "0 20px 40px rgba(14, 59, 105, 0.06)",
        "editorial-xl": "0 30px 60px rgba(14, 59, 105, 0.12)",
      },
    },
  },
  plugins: [],
};
